import './globals.css';
import DesktopNav from '../components/Nav/DesktopNav';
import Provider from './provider';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <DesktopNav />
        <Provider>
          {children}
        </Provider>
        <footer>
          footer
        </footer>
      </body>
    </html>
  );
}
